### ISSUE TITLE
apache url issue mod rewrite

### ISSUE THREAD

**Issue by ivo1981** [chintanbanugaria/92five#111]
I have a problem with the images in assets not showing.
the url looks like:
domain.com/index.php/assets/images/dashboard/circle_1.png
it should be 
domain.com/assets/images/dashboard/circle_1.png
this is an issue al over the site. I have used the .htaccess that is provided and I can confirm apache uses it.
Any suggestions on how I can fix this?

**Comment by ivo1981** [comment]
made a rule in .htacces that rewrites all requests to  domain.com/index.php/assets/ to domain.com/assets/

**Comment by chintanbanugaria** [comment]
Sorry for late reply. Please make PR so that I can merge it accordingly. 
Thanks.
