### ISSUE TITLE
Exact dates should not be enforced

### ISSUE THREAD

**Issue by blurmonk** [chintanbanugaria/92five#3]
Hi
I do not see any reason why the dates are enforced on the tasks and projects. For one the dates can be calculated based on subtask progress. Also this makes the system very rigid.

It is looking nice btw. 

thanks

**Comment by crunchprank** [comment]
This is my single most common gripe with task / project management. I work in an environment where we want to be able to just throw projects that need to be worked on into some sort of platform / solution. We don't have dates in mind that they need to be completed by - we just want a place to document the tasks and assign them to each other. Is there any plans to implement this?

**Comment by chintanbanugaria** [comment]
This issue has been resolved in the next version which is due to launch at the end of this month :)
