### ISSUE TITLE
Updating to Laravel 5.0

### ISSUE THREAD

**Issue by austinkregel** [chintanbanugaria/92five#90]
Hello, I was wondering if there was any way this project could be updated to Laravel 5.0

**Comment by austinkregel** [comment]
@conceptuli is there anyway you might be able to fulfil this request, I noticed that your repo was much more active than this one.

**Comment by chintanbanugaria** [comment]
@austinkregel  Mate composer.json has already been added to the repo. Please have a look again else you can find it here https://github.com/chintanbanugaria/92five/blob/master/composer.json

Regarding updating to L5, I am developing the next version with more features awesome UI on L5. I am stuck up with some family issues thats the reason I have pushed any updates on the repo. Will update the same soon.

Thanks.

**Comment by austinkregel** [comment]
Okay thank you, and I saw the composer file after I had another look.

**Comment by austinkregel** [comment]
Is there anyway you would be willing to make a branch and upload a bleeding edge version of the 5.0 version you have (if you have one)

**Comment by knolaust** [comment]
I've been wanting to use this app for project management, but I don't want to commit until the next release. Any ETA on the L5 version?

**Comment by austinkregel** [comment]
As far as I can tell the author became busy again. I would recommend just using this version and then make the switch later on. That's what I am going to do.

**Comment by knolaust** [comment]
Apparently not too busy. There were features added 7 hours ago.

**Comment by austinkregel** [comment]
@knolaust Looks like it will be around the first week of June. http://forums.92fiveapp.com/?p=90-next-version-release
